version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - data-provider

  data-provider:
    image: sytacdocker/video-stream-server-arm:latest
    ports:
      - "8080:8080"